version: "3.9"

services:
  postgres:
    image: postgres:15.4
    volumes:
      - .volumes/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  application:
    build: .
    container_name: taxi
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/taxi
      RABBIT_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitMQ
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=email
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 30s
#      retries: 3
