spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/taxi
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

#        authenticationspring
